github: [devinschumacher]
open_collective: devinschumacher
custom: [
"https://apps.serp.co/beeg-video-downloader",
"https://orangepornvideos.net/beeg-video-downloader",
"https://downloadingfreevideo.com/beeg-video-downloader",
"https://serp.co/products/beeg-video-downloader/reviews/",
]
